Fetching All Categories
HOVA-INTERNSHIP-PROGRAM/hovastore-support-fe pull request #11
Opened 2024-04-01 17:38 UTC by muhozajohn

### What does this PR do?
This PR fetching categories  on  landing page

### Description of Task completed?
- Re usable Input
- Re Usable Button
- solution slices

### How should this be manually tested?
- Checkout branch `feature/ft-fetching/U97oTUEX`
- Install packages, and run `npm start`

### Screenshots 
![image](https://github.com/HOVA-INTERNSHIP-PROGRAM/hovastore-support-fe/assets/87951014/b613511a-a41b-491a-a811-12864952650e)
| ------ | ------ |
| ------ | ------ |

2024-04-02 19:01 UTC, alicepretty submitted a review, later dismissed
Hey @muhozajohn  , i reviewed your PR, so far everything is working well .but i recommend you to create your loader without using  package , u can use tailwind css.

2024-04-02 21:00 UTC, muhozajohn commented
> Hey @muhozajohn , i reviewed your PR, so far everything is working well .but i recommend you to create your loader without using package , u can use tailwind css.

hey @alicepretty You can check Again We Already Done With It

2024-04-02 22:03 UTC, ncutixavier requested changes

2024-04-02 22:03 UTC, ncutixavier commented on src/components/Loading.jsx
> +// export default Loading;
Unnecessary comments

2024-04-02 22:03 UTC, ncutixavier commented on src/components/NoData.jsx
> +export default NoData;
Can we have a custom page, @kunda-pauline & @muhozajohn

2024-04-02 22:03 UTC, ncutixavier commented on package.json
> +    "react-spinners": "^0.13.8",
Avoid using many unnecessary packages. 
- What `framer-motion` does?
- Do we need this `react-spinners`?

2024-04-02 22:03 UTC, ncutixavier commented on src/axiosInstance.js
> +  baseURL: "https://hovastore-support-be.onrender.com/api/v1",
Can we put this in the environment variables?

2024-04-02 22:03 UTC, ncutixavier commented on src/components/Skeleton.js
- Since we're going to have multiple skeletons, let's have a folder inside the components
- This file should be renamed based on where skeleton is going to used

2024-04-02 22:03 UTC, ncutixavier commented on src/components/UI/Input.jsx
Since all files inside UI are custom components, Let's rename each custom component with a prefix of HS
`Input => HSInput`

2024-04-02 22:03 UTC, ncutixavier commented on src/features/solutions/getAllSolutionsSlice.js
> +    },
- Status should not be a string
- Refactor your `initialState` based on below example
```
initialState: {
    books: [],
    loading: false,
    error: null,
  },
```

2024-04-02 22:03 UTC, ncutixavier commented on src/services/solution.service.jsx
Nice implementation!

2024-04-02 22:25 UTC, muhozajohn commented
I think spinner wil be Needed on Button while we user making request

Other Requested I will Work on It Tomorrow

On Wed, Apr 3, 2024, 12:03 AM Ncuti Xavier ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In src/components/Loading.jsx
> <https://github.com/HOVA-INTERNSHIP-PROGRAM/hovastore-support-fe/pull/11#discussion_r1548649659>
> :
>
> > +// import HashLoader from "react-spinners/HashLoader";
> +
> +// const Loading = () => {
> +//   return (
> +//     <div className=" py-3 w-full flex justify-center items-center ">
> +//       <HashLoader color="#581845" loading={true} size={20} />
> +//     </div>
> +//   );
> +// };
> +
> +// export default Loading;
>
> Unnecessary comments
> ------------------------------
>
> In src/components/NoData.jsx
> <https://github.com/HOVA-INTERNSHIP-PROGRAM/hovastore-support-fe/pull/11#discussion_r1548650458>
> :
>
> > +const NoData = () => {
> +  return (
> +    <div className="flex flex-col justify-center items-center min-h-screen font-semibold text-2xl">
> +      NoData Found
> +    </div>
> +  );
> +};
> +
> +export default NoData;
>
> Can we have a custom page, @kunda-pauline
> <https://github.com/kunda-pauline> & @muhozajohn
> <https://github.com/muhozajohn>
> ------------------------------
>
> In package.json
> <https://github.com/HOVA-INTERNSHIP-PROGRAM/hovastore-support-fe/pull/11#discussion_r1548651735>
> :
>
> > @@ -17,6 +18,7 @@
>      "react-redux": "^9.1.0",
>      "react-router-dom": "^6.22.3",
>      "react-scripts": "5.0.1",
> +    "react-spinners": "^0.13.8",
>
> Avoid using many unnecessary packages.
>
>    - What framer-motion does?
>    - Do we need this react-spinners?
>
> ------------------------------
>
> In src/axiosInstance.js
> <https://github.com/HOVA-INTERNSHIP-PROGRAM/hovastore-support-fe/pull/11#discussion_r1548652404>
> :
>
> > @@ -1,9 +1,7 @@
>  import axios from "axios";
>
>  const http = axios.create({
> -  baseURL: "https://leave-backend.onrender.com/api/v1",
> -  // baseURL: "http://localhost:3005/api/v1",
> -  // baseURL: "https://nx-leave-backend.cleverapps.io/api/v1",
> +  baseURL: "https://hovastore-support-be.onrender.com/api/v1",
>
> Can we put this in the environment variables?
> ------------------------------
>
> On src/components/Skeleton.js
> <https://github.com/HOVA-INTERNSHIP-PROGRAM/hovastore-support-fe/pull/11#discussion_r1548654833>
> :
>
>    - Since we're going to have multiple skeletons, let's have a folder
>    inside the components
>    - This file should be renamed based on where skeleton is going to used
>
> ------------------------------
>
> On src/components/UI/Input.jsx
> <https://github.com/HOVA-INTERNSHIP-PROGRAM/hovastore-support-fe/pull/11#discussion_r1548659555>
> :
>
> Since all files inside UI are custom components, Let's rename each custom
> component with a prefix of HS
> Input => HSInput
> ------------------------------
>
> In src/features/solutions/getAllSolutionsSlice.js
> <https://github.com/HOVA-INTERNSHIP-PROGRAM/hovastore-support-fe/pull/11#discussion_r1548665504>
> :
>
> > +    extraReducers: (builder) => {
> +        builder
> +            .addCase(getAllSolutions.pending, (state) => {
> +                state.status = 'loading';
> +            })
> +            .addCase(getAllSolutions.fulfilled, (state, action) => {
> +                state.status = "succeeded";
> +                state.solutions = action.payload;
> +            })
> +            .addCase(getAllSolutions.rejected, (state, action) => {
> +                state.status = 'failed';
> +                state.error = action.error.message;
> +            })
> +    },
>
>
>    - Status should not be a string
>    - Refactor your initialState based on below example
>
> initialState: {
>     books: [],
>     loading: false,
>     error: null,
>   },
>
> ------------------------------
>
> On src/services/solution.service.jsx
> <https://github.com/HOVA-INTERNSHIP-PROGRAM/hovastore-support-fe/pull/11#discussion_r1548667678>
> :
>
> Nice implementation!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/HOVA-INTERNSHIP-PROGRAM/hovastore-support-fe/pull/11#pullrequestreview-1975121633>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AU7ANJR4BBXF7YP7ISUB7MDY3MTMFAVCNFSM6AAAAABFR57CEWVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTSNZVGEZDCNRTGM>
> .
> You are receiving this because you were mentioned.Message ID:
> <HOVA-INTERNSHIP-PROGRAM/hovastore-support-fe/pull/11/review/1975121633@
> github.com>
>

2024-04-02 22:29 UTC, muhozajohn commented on package.json
> +    "react-spinners": "^0.13.8",
Spinner Will be needed on Button while user Making Request

2024-04-02 22:29 UTC, muhozajohn commented on src/components/NoData.jsx
> +export default NoData;
We make Drafts on It

2024-04-02 22:35 UTC, ncutixavier commented
There is a way, we can handle the button spinner with tailwind

2024-04-11 19:18 UTC, ncutixavier approved these changes

2024-04-11 19:57 UTC, ncutixavier approved these changes

2024-04-11 19:58 UTC, merged